### PR TITLE
 Use actual unions instead of object with optional keys

### LINKED ISSUE #3: Use TypeScript unions to represent Ledger API's `oneof`s
Right now Ledger API's `oneof`s (that is, union types) are represented by objects with exclusively optional keys. This is not type-safe, error prone and hardly self-documenting. TypeScript supports union types, and those should be used to represent `oneof`s. A possible way to go is to use [discriminated unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions).

### PR DESCRIPTION
**Pull request by stefanobaghino-da**
Fixes #3

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
> digital-asset.daml-js Successful in 45s — Build #20190425.10 succeeded
By the way, I'm very happy about the CI response time.

**Comment by stefanobaghino-da** [comment]
After a brief discussion with @bitonic, the following points will be covered in an upcoming commit:

- [ ] use a bespoke type tag for each union instead of `__type__` for all of them: this makes the resulting objects more readable and removes any risk of name clashes in the future, even in the worst-case scenario of having to introduce a `__type__` field in an union on the Ledger API
- [ ] (optional) add helpers to construct values more easily (e.g. a `record` function that takes splatted fields and constructs a valid Ledger API record without the user having to build the whole object by hand)

**Comment by rautenrieth-da** [comment]
Out of interest, does the compiler check for exhaustiveness of your `switch (object.__type__)` blocks?
Navigator uses a [special compiler trick](https://github.com/digital-asset/daml/blob/master/navigator/frontend/src/ui-core/src/util.tsx#L42) to get compile errors if the match is not exhaustive, but this might not be necessary with the recent TypeScript version.

**Comment by stefanobaghino-da** [comment]
> Out of interest, does the compiler check for exhaustiveness of your `switch (object.__type__)` blocks?
> Navigator uses a [special compiler trick](https://github.com/digital-asset/daml/blob/master/navigator/frontend/src/ui-core/src/util.tsx#L42) to get compile errors if the match is not exhaustive, but this might not be necessary with the recent TypeScript version.

[Yup.](https://www.typescriptlang.org/docs/handbook/advanced-types.html#exhaustiveness-checking)

**Pull request merged**
